[2025-08-29T14:48:34.312+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:48:22+00:00 [queued]>
[2025-08-29T14:48:34.317+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:48:22+00:00 [queued]>
[2025-08-29T14:48:34.317+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T14:48:34.317+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-29T14:48:34.317+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T14:48:34.322+0000] {taskinstance.py:1300} INFO - Executing <Task(AirbyteConnectionCreator): create_airbyte_connection> on 2025-08-29 14:48:22+00:00
[2025-08-29T14:48:34.324+0000] {standard_task_runner.py:55} INFO - Started process 21950 to run task
[2025-08-29T14:48:34.326+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_airbyte_connection', 'manual__2025-08-29T14:48:22+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmp6uk3763b']
[2025-08-29T14:48:34.326+0000] {standard_task_runner.py:83} INFO - Job 152: Subtask create_airbyte_connection
[2025-08-29T14:48:34.354+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:48:22+00:00 [running]> on host 966b32814b47
[2025-08-29T14:48:34.382+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_airbyte_connection
AIRFLOW_CTX_EXECUTION_DATE=2025-08-29T14:48:22+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-29T14:48:22+00:00
[2025-08-29T14:48:34.382+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 118, in poke
    self.create_airbyte_connection(context)
TypeError: create_airbyte_connection() takes 0 positional arguments but 2 were given
[2025-08-29T14:48:34.385+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=create_airbyte_connection, execution_date=20250829T144822, start_date=20250829T144834, end_date=20250829T144834
[2025-08-29T14:48:34.390+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 152 for task create_airbyte_connection (create_airbyte_connection() takes 0 positional arguments but 2 were given; 21950)
[2025-08-29T14:48:34.423+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-08-29T14:48:34.436+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
