[2025-09-03T18:39:17.841+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_custom_source_and_discover_schema manual__2025-09-03T18:39:10+00:00 [queued]>
[2025-09-03T18:39:17.853+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_custom_source_and_discover_schema manual__2025-09-03T18:39:10+00:00 [queued]>
[2025-09-03T18:39:17.854+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T18:39:17.854+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-09-03T18:39:17.854+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T18:39:17.861+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_custom_source_and_discover_schema> on 2025-09-03 18:39:10+00:00
[2025-09-03T18:39:17.863+0000] {standard_task_runner.py:55} INFO - Started process 221717 to run task
[2025-09-03T18:39:17.865+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_custom_source_and_discover_schema', 'manual__2025-09-03T18:39:10+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmp1hqnf44l']
[2025-09-03T18:39:17.866+0000] {standard_task_runner.py:83} INFO - Job 191: Subtask create_custom_source_and_discover_schema
[2025-09-03T18:39:17.897+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_custom_source_and_discover_schema manual__2025-09-03T18:39:10+00:00 [running]> on host 966b32814b47
[2025-09-03T18:39:17.934+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_custom_source_and_discover_schema
AIRFLOW_CTX_EXECUTION_DATE=2025-09-03T18:39:10+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-03T18:39:10+00:00
[2025-09-03T18:39:18.093+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 34, in create_custom_source_and_discover_schema
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://host.docker.internal:8001/api/v1/sources/create
[2025-09-03T18:39:18.101+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=create_custom_source_and_discover_schema, execution_date=20250903T183910, start_date=20250903T183917, end_date=20250903T183918
[2025-09-03T18:39:18.111+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 191 for task create_custom_source_and_discover_schema (404 Client Error: Not Found for url: http://host.docker.internal:8001/api/v1/sources/create; 221717)
[2025-09-03T18:39:18.125+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-09-03T18:39:18.145+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
