[2025-08-28T07:09:55.898+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-28T07:09:54.720757+00:00 [queued]>
[2025-08-28T07:09:55.903+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-28T07:09:54.720757+00:00 [queued]>
[2025-08-28T07:09:55.903+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-28T07:09:55.903+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-28T07:09:55.903+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-28T07:09:55.909+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_airbyte_connection> on 2025-08-28 07:09:54.720757+00:00
[2025-08-28T07:09:55.911+0000] {standard_task_runner.py:55} INFO - Started process 26324 to run task
[2025-08-28T07:09:55.913+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_airbyte_connection', 'manual__2025-08-28T07:09:54.720757+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmpnvi8lqdg']
[2025-08-28T07:09:55.913+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask create_airbyte_connection
[2025-08-28T07:09:55.938+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-28T07:09:54.720757+00:00 [running]> on host 966b32814b47
[2025-08-28T07:09:55.964+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_airbyte_connection
AIRFLOW_CTX_EXECUTION_DATE=2025-08-28T07:09:54.720757+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-28T07:09:54.720757+00:00
[2025-08-28T07:09:55.965+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 56, in create_airbyte_connection
    "selected": true,
NameError: name 'true' is not defined
[2025-08-28T07:09:55.968+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=create_airbyte_connection, execution_date=20250828T070954, start_date=20250828T070955, end_date=20250828T070955
[2025-08-28T07:09:55.972+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task create_airbyte_connection (name 'true' is not defined; 26324)
[2025-08-28T07:09:56.013+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-08-28T07:09:56.023+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
