[2025-08-28T07:07:53.975+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-28T07:07:52.919403+00:00 [queued]>
[2025-08-28T07:07:53.981+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-28T07:07:52.919403+00:00 [queued]>
[2025-08-28T07:07:53.981+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-28T07:07:53.982+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-28T07:07:53.982+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-28T07:07:53.987+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_airbyte_connection> on 2025-08-28 07:07:52.919403+00:00
[2025-08-28T07:07:53.990+0000] {standard_task_runner.py:55} INFO - Started process 26078 to run task
[2025-08-28T07:07:53.993+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_airbyte_connection', 'manual__2025-08-28T07:07:52.919403+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmp9dy2qohg']
[2025-08-28T07:07:53.993+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask create_airbyte_connection
[2025-08-28T07:07:54.021+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-28T07:07:52.919403+00:00 [running]> on host 966b32814b47
[2025-08-28T07:07:54.047+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_airbyte_connection
AIRFLOW_CTX_EXECUTION_DATE=2025-08-28T07:07:52.919403+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-28T07:07:52.919403+00:00
[2025-08-28T07:07:54.048+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 46, in create_airbyte_connection
    "sourceDefinedCursor": true,
NameError: name 'true' is not defined
[2025-08-28T07:07:54.051+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=create_airbyte_connection, execution_date=20250828T070752, start_date=20250828T070753, end_date=20250828T070754
[2025-08-28T07:07:54.055+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task create_airbyte_connection (name 'true' is not defined; 26078)
[2025-08-28T07:07:54.092+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-08-28T07:07:54.104+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
