[2025-08-26T12:40:33.815+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-26T12:40:33.132506+00:00 [queued]>
[2025-08-26T12:40:33.822+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-26T12:40:33.132506+00:00 [queued]>
[2025-08-26T12:40:33.822+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-26T12:40:33.822+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-26T12:40:33.822+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-26T12:40:33.827+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_airbyte_connection> on 2025-08-26 12:40:33.132506+00:00
[2025-08-26T12:40:33.830+0000] {standard_task_runner.py:55} INFO - Started process 6238 to run task
[2025-08-26T12:40:33.831+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_airbyte_connection', 'manual__2025-08-26T12:40:33.132506+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmp7dg6ex_3']
[2025-08-26T12:40:33.832+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_airbyte_connection
[2025-08-26T12:40:33.854+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-26T12:40:33.132506+00:00 [running]> on host 966b32814b47
[2025-08-26T12:40:33.879+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_airbyte_connection
AIRFLOW_CTX_EXECUTION_DATE=2025-08-26T12:40:33.132506+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-26T12:40:33.132506+00:00
[2025-08-26T12:40:33.880+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 25, in create_airbyte_connection
    response = hook._client.request("/connections/create", data=payload)
AttributeError: 'AirbyteHook' object has no attribute '_client'
[2025-08-26T12:40:33.883+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=create_airbyte_connection, execution_date=20250826T124033, start_date=20250826T124033, end_date=20250826T124033
[2025-08-26T12:40:33.887+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_airbyte_connection ('AirbyteHook' object has no attribute '_client'; 6238)
[2025-08-26T12:40:33.933+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-08-26T12:40:33.944+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
