[2025-08-28T11:12:32.140+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.wait_for_airbyte_idle manual__2025-08-28T11:12:26.064462+00:00 [queued]>
[2025-08-28T11:12:32.147+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.wait_for_airbyte_idle manual__2025-08-28T11:12:26.064462+00:00 [queued]>
[2025-08-28T11:12:32.147+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-28T11:12:32.147+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-28T11:12:32.147+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-28T11:12:32.157+0000] {taskinstance.py:1300} INFO - Executing <Task(AirbyteJobSensor): wait_for_airbyte_idle> on 2025-08-28 11:12:26.064462+00:00
[2025-08-28T11:12:32.160+0000] {standard_task_runner.py:55} INFO - Started process 47116 to run task
[2025-08-28T11:12:32.162+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'wait_for_airbyte_idle', 'manual__2025-08-28T11:12:26.064462+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmp28y9uhf_']
[2025-08-28T11:12:32.163+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask wait_for_airbyte_idle
[2025-08-28T11:12:32.207+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.wait_for_airbyte_idle manual__2025-08-28T11:12:26.064462+00:00 [running]> on host 966b32814b47
[2025-08-28T11:12:32.254+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=wait_for_airbyte_idle
AIRFLOW_CTX_EXECUTION_DATE=2025-08-28T11:12:26.064462+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-28T11:12:26.064462+00:00
[2025-08-28T11:12:32.289+0000] {logging_mixin.py:137} INFO - Airbyte API error: 500 {"message":"Internal Server Error: Must include at least one configType.","exceptionClassName":"java.lang.IllegalStateException","exceptionStack":[],"rootCauseExceptionStack":[]}
[2025-08-28T11:12:32.290+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 30, in poke
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://host.docker.internal:8001/api/v1/jobs/list
[2025-08-28T11:12:32.297+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=wait_for_airbyte_idle, execution_date=20250828T111226, start_date=20250828T111232, end_date=20250828T111232
[2025-08-28T11:12:32.306+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 34 for task wait_for_airbyte_idle (500 Server Error: Internal Server Error for url: http://host.docker.internal:8001/api/v1/jobs/list; 47116)
[2025-08-28T11:12:32.339+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-08-28T11:12:32.354+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
