[2025-08-29T14:47:34.938+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:47:19+00:00 [queued]>
[2025-08-29T14:47:34.944+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:47:19+00:00 [queued]>
[2025-08-29T14:47:34.944+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T14:47:34.944+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-29T14:47:34.944+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T14:47:34.949+0000] {taskinstance.py:1300} INFO - Executing <Task(AirbyteConnectionCreator): create_airbyte_connection> on 2025-08-29 14:47:19+00:00
[2025-08-29T14:47:34.951+0000] {standard_task_runner.py:55} INFO - Started process 21844 to run task
[2025-08-29T14:47:34.953+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_airbyte_connection', 'manual__2025-08-29T14:47:19+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmpqay8smwq']
[2025-08-29T14:47:34.954+0000] {standard_task_runner.py:83} INFO - Job 149: Subtask create_airbyte_connection
[2025-08-29T14:47:34.983+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:47:19+00:00 [running]> on host 966b32814b47
[2025-08-29T14:47:35.017+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_airbyte_connection
AIRFLOW_CTX_EXECUTION_DATE=2025-08-29T14:47:19+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-29T14:47:19+00:00
[2025-08-29T14:47:35.017+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 118, in poke
    self.create_connection(context)
AttributeError: 'AirbyteConnectionCreator' object has no attribute 'create_connection'
[2025-08-29T14:47:35.021+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=create_airbyte_connection, execution_date=20250829T144719, start_date=20250829T144734, end_date=20250829T144735
[2025-08-29T14:47:35.026+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 149 for task create_airbyte_connection ('AirbyteConnectionCreator' object has no attribute 'create_connection'; 21844)
[2025-08-29T14:47:35.055+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-08-29T14:47:35.068+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
