[2025-08-29T14:42:45.612+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:42:21+00:00 [queued]>
[2025-08-29T14:42:45.619+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:42:21+00:00 [queued]>
[2025-08-29T14:42:45.619+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T14:42:45.619+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-29T14:42:45.619+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T14:42:45.625+0000] {taskinstance.py:1300} INFO - Executing <Task(AirbyteConnectionCreator): create_airbyte_connection> on 2025-08-29 14:42:21+00:00
[2025-08-29T14:42:45.628+0000] {standard_task_runner.py:55} INFO - Started process 21354 to run task
[2025-08-29T14:42:45.629+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_airbyte_connection', 'manual__2025-08-29T14:42:21+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmpz3kp47fd']
[2025-08-29T14:42:45.630+0000] {standard_task_runner.py:83} INFO - Job 144: Subtask create_airbyte_connection
[2025-08-29T14:42:45.662+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-29T14:42:21+00:00 [running]> on host 966b32814b47
[2025-08-29T14:42:45.702+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_airbyte_connection
AIRFLOW_CTX_EXECUTION_DATE=2025-08-29T14:42:21+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-29T14:42:21+00:00
[2025-08-29T14:42:45.703+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/opt/airflow/dags/dynamic-airbyte-with-airflow.py", line 116, in poke
    if not self.connection_id:
AttributeError: 'AirbyteConnectionCreator' object has no attribute 'connection_id'
[2025-08-29T14:42:45.708+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_dynamic_connection, task_id=create_airbyte_connection, execution_date=20250829T144221, start_date=20250829T144245, end_date=20250829T144245
[2025-08-29T14:42:45.719+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 144 for task create_airbyte_connection ('AirbyteConnectionCreator' object has no attribute 'connection_id'; 21354)
[2025-08-29T14:42:45.727+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-08-29T14:42:45.752+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
