[2025-08-26T13:04:27.887+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-26T13:04:27.016416+00:00 [queued]>
[2025-08-26T13:04:27.892+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-26T13:04:27.016416+00:00 [queued]>
[2025-08-26T13:04:27.893+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-08-26T13:04:27.893+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-08-26T13:04:27.893+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-08-26T13:04:27.898+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_airbyte_connection> on 2025-08-26 13:04:27.016416+00:00
[2025-08-26T13:04:27.901+0000] {standard_task_runner.py:55} INFO - Started process 8820 to run task
[2025-08-26T13:04:27.902+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dynamic_connection', 'create_airbyte_connection', 'manual__2025-08-26T13:04:27.016416+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dynamic-airbyte-with-***.py', '--cfg-path', '/tmp/tmpw37veofz']
[2025-08-26T13:04:27.903+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_airbyte_connection
[2025-08-26T13:04:27.929+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_dynamic_connection.create_airbyte_connection manual__2025-08-26T13:04:27.016416+00:00 [running]> on host 966b32814b47
[2025-08-26T13:04:27.953+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_dynamic_connection
AIRFLOW_CTX_TASK_ID=create_airbyte_connection
AIRFLOW_CTX_EXECUTION_DATE=2025-08-26T13:04:27.016416+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-26T13:04:27.016416+00:00
[2025-08-26T13:13:16.884+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-08-26T13:13:16.886+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 8820. PIDs of all processes in the group: [8820]
[2025-08-26T13:13:16.886+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 8820
[2025-08-26T13:13:16.887+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-26T13:13:16.945+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8820, status='terminated', exitcode=0, started='13:04:27') (8820) terminated with exit code 0
