{"timestamp":"2025-09-04T11:21:42.241117","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-04T11:21:42.241759","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dynamic-airbyte-with-airflow.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-04T11:21:44.001063","level":"info","event":"Trying to parse the dbt project using dbt ls cache cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11...","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:21:44.173755","level":"info","event":"Cosmos performance: time to calculate cache identifier cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11 for current version: 0.08343583298847079","logger":"cosmos.cache"}
{"timestamp":"2025-09-04T11:21:44.174032","level":"info","event":"Cosmos performance [2b2e84620275|1416]: The cache size for cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11 is 4335","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:21:44.174353","level":"info","event":"Cosmos performance: Cache hit for cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11 - aad8d04d72ff7b6917b24f4cd2f34a0b,d41d8cd98f00b204e9800998ecf8427e","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:21:44.177047","level":"info","event":"Total nodes: 6","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:21:44.177142","level":"info","event":"Total filtered nodes: 6","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:21:44.177232","level":"info","event":"Cosmos performance (airbyte_dynamic_connection__my_project_dbt_group_11) -  [2b2e84620275|1416]: It took 0.177s to parse the dbt project for DAG using LoadMode.DBT_LS_CACHE","logger":"cosmos.converter"}
{"timestamp":"2025-09-04T11:21:44.179054","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:21:44.180319","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:21:44.183263","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:21:44.185550","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:21:44.186490","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:21:44.187448","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:21:44.188853","level":"info","event":"Cosmos performance (airbyte_dynamic_connection__my_project_dbt_group_11) - [2b2e84620275|1416]: It took 0.0116s to build the Airflow DAG.","logger":"cosmos.converter"}
{"timestamp":"2025-09-04T11:21:44.191134","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:\n  PydanticSerializationUnexpectedValue(Expected `str` - serialized value may not be as expected [input_value={'version': 'aad8d04d72ff...y_project_dbt_group_11'}, input_type=dict])\n  return self.__pydantic_serializer__.to_python(\n","logger":"py.warnings"}
{"timestamp":"2025-09-04T11:21:44.227882Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:44.228352Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:44.228840Z","level":"info","event":"Current task name:my_project_dbt_group_11.stg_weather_data_run","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:44.229437Z","level":"info","event":"Dag name:airbyte_dynamic_connection","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:45.837281","level":"info","event":"dbtRunner is available. Using dbtRunner for invoking dbt.","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:21:45.838601","level":"info","event":"Cloning project to writable temp directory /tmp/tmp6vvba7_s from /opt/airflow/dbt/my_project_dbt","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:21:45.842447","level":"info","event":"Partial parse is enabled and the latest partial parse file is /opt/airflow/dbt/my_project_dbt/target/partial_parse.msgpack","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:21:45.850110","level":"info","event":"Profile caching is enable.","logger":"cosmos.config"}
{"timestamp":"2025-09-04T11:21:45.861254","level":"info","event":"Connection Retrieved 'test-airbyte-and-dbt-with-airflow'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-04T11:21:45.861754","level":"info","event":"Using real values for profile dbt_postgres_profile","logger":"cosmos.profiles.base"}
{"timestamp":"2025-09-04T11:21:45.862644","level":"info","event":"Profile not found in cache storing and using profile: /tmp/cosmos/profile/922021775909dd134e724f780b41e87fc6d4989e8d9e38bd82f43f7a68edaf2a/profiles.yml.","logger":"cosmos.config"}
{"timestamp":"2025-09-04T11:21:45.863297","level":"info","event":"Trying to run dbtRunner with:\n ['run', '--select', 'stg_weather_data', '--project-dir', '/tmp/tmp6vvba7_s', '--profiles-dir', '/tmp/cosmos/profile/922021775909dd134e724f780b41e87fc6d4989e8d9e38bd82f43f7a68edaf2a', '--profile', 'dbt_postgres_profile', '--target', 'dev', '--no-static-parser']\n in /tmp/tmp6vvba7_s","logger":"cosmos.dbt.runner"}
{"timestamp":"2025-09-04T11:21:45.890655Z","level":"info","event":"\u001b[0m11:21:45  Running with dbt=1.8.2","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:46.116241Z","level":"info","event":"\u001b[0m11:21:46  Registered adapter: postgres=1.8.2","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:46.509785Z","level":"info","event":"\u001b[0m11:21:46  Unable to do partial parsing because of a version mismatch","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.065314Z","level":"info","event":"\u001b[0m11:21:47  Found 5 models, 1 source, 428 macros","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.067342Z","level":"info","event":"\u001b[0m11:21:47","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.114637Z","level":"info","event":"\u001b[0m11:21:47","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.115897Z","level":"info","event":"\u001b[0m11:21:47  Finished running  in 0 hours 0 minutes and 0.05 seconds (0.05s).","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.116326Z","level":"info","event":"\u001b[0m11:21:47  Encountered an error:","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.116869Z","level":"info","event":"Database Error","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.117112Z","level":"info","event":"  connection to server at \"host.docker.internal\" (192.168.65.254), port 5391 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.117453Z","level":"info","event":"  \tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:47.117783Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.159187","level":"info","event":"Inlets: []","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:21:48.159429","level":"info","event":"Outlets: []","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:21:48.159786","level":"info","event":"Assigning outlets with DatasetAlias in Airflow 3","logger":"cosmos.operators.local"}
{"timestamp":"2025-09-04T11:21:48.163616","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CosmosDbtRunError","exc_value":"dbt invocation did not complete with unhandled error: Database Error\n  connection to server at \"host.docker.internal\" (192.168.65.254), port 5391 failed: Connection refused\n  \tIs the server running on that host and accepting TCP/IP connections?\n  ","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":918,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1213,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py","lineno":310,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py","lineno":851,"name":"build_and_run_cmd"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py","lineno":648,"name":"run_command"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py","lineno":258,"name":"handle_exception_dbt_runner"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/dbt/runner.py","lineno":109,"name":"handle_exception_if_needed"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-04T11:21:48.204669Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.204936Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.205070Z","level":"info","event":"Task:<Task(DbtRunLocalOperator): my_project_dbt_group_11.stg_weather_data_run>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.205205Z","level":"info","event":"Failure caused by dbt invocation did not complete with unhandled error: Database Error","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.205319Z","level":"info","event":"  connection to server at \"host.docker.internal\" (192.168.65.254), port 5391 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.205436Z","level":"info","event":"  \tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.205514Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.227690Z","level":"error","event":"/usr/local/lib/python3.12/multiprocessing/resource_tracker.py:279: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-04T11:21:48.227889Z","level":"error","event":"  warnings.warn('resource_tracker: There appear to be %d '","chan":"stderr","logger":"task"}
